### ISSUE TITLE
Matrix4::Inverse error

### ISSUE THREAD

**Issue by richtw1** [Isetta-Team/Isetta-Engine#2]
https://github.com/Isetta-Team/Isetta-Engine/blob/fa57b233ddd85d7c4f533dbeef2fdaaf47bb0a92/Isetta/IsettaEngine/Core/Math/Matrix4.cpp#L327

Should be (1.f / det)!

**Comment by zhuyidiwow** [comment]
Thank you for opening this issue! It's fixed in commit [6f670f01](https://github.com/Isetta-Team/Isetta-Engine/commit/6f670f0159b0fd49dcda23dfbef5ebd8336b2309#diff-5073704173c772c73aa262b9062d0435).

By the way, we just pushed up our week 9 tag, feel free to check it out!
