### ISSUE TITLE
Random Magic Number in Memory Reservation?

### ISSUE THREAD

**Issue by Aleksbgbg** [Isetta-Team/Isetta-Engine#3]
Wanted to ask about this array allocation in `StackAllocator.h`:
https://github.com/Isetta-Team/Isetta-Engine/blob/bd461216740d6191dd53652deae0645f48488828/Isetta/IsettaEngine/Core/Memory/StackAllocator.h#L75-L81

Specifically on line 77, why is the calculation `sizeof(T) * length + 8` instead of simply `sizeof(T) * length`?

I'm unsure whether this relates to alignment or it is there for another reason.

If you *do* know, it would be a good idea to insert a comment to explain the magic number.

In addition, I noticed that this method was refactored from a `new () T[length]`  call to a custom loop as per this diff: https://github.com/Isetta-Team/Isetta-Engine/commit/a8adda47c97a1785dd01d1d5cf341cb5078c4e50#diff-7daa528982dcd977e1a44dbd9f1167f5L84.

Was there a reason for this? The commit did not specify.

**Comment by zackszhu** [comment]
For your second question about refactoring the new call, we had a section here in our [blog post](https://isetta.io/blogs/week-10/#placement-new-for-arrays-is-undefined). It is because the placement new for arrays is unclear.

**Comment by Aleksbgbg** [comment]
Thanks for letting me know! I will definitely keep this in mind.

I would also be quite interested to know why the `+8` is there if/when you can find out.

Thanks!

**Comment by cbiasco** [comment]
Hm...honestly? I think that magic number 8 might be a holdover from when we were trying to figure out why array allocations were going weird. If you read the blog post that zackszhu posted, you'll see that our initial findings was our arrays were getting an extra 8 bytes allocated.

When we get the time, we should try removing that and seeing if everything runs okay... (or you could try it yourself, Aleksbgbg, if our instructions for building the engine aren't too difficult to follow :P)

**Comment by Aleksbgbg** [comment]
@cbiasco just tested it - the IsettaTestBed project works exactly the same whether or not the `+8` is there.

Does that make sense? I would say this means that the `+8` was a leftover, but I can't be sure.

**Comment by cbiasco** [comment]
Yep that makes sense. We left it in there on accident haha. (That happens way more often that you'd probably like to believe...)

I'll patch that. Thanks for raising it up to us!

**Comment by zhuyidiwow** [comment]
I just had a noon nap and woke up to see another bug fixed, nice job guys!
